#!/bin/bash

USER_MESSAGE="
$(basename $0) [-h | -clean | -eikonal3D_gpu ]

-h --help          Show all instructions
-eikonal3D_gpu     Compile and run 3D GPU eikonal application 
-tomography3D_gpu  Compile and run 3D GPU tomography application 

Usage: 

bash$ $0 -eikonal3D_gpu      # Compile and run .cpp files
bash$ $0 -tomography3D_gpu   # Compile and run .cpp files
"

inout=src/essentials/inout/inout.cpp
model=src/essentials/model/model.cpp
utils=src/essentials/utils/utils.cpp
geom=src/essentials/geometry/geometry.cpp

# Check if user provide some parameter
[ -z "$1" ] && {
	echo " "
	echo "The user doesn't provide any parameter" 
	echo "Type $0 -h for more info"
	echo " "  
	exit 1 
}

case "$1" in
-h | --help) ## Show help
	echo -e "$USER_MESSAGE"
	exit 0
;;

-clean) ## Remove files .bin 


	exit 0
;;

-eikonal3D_gpu) ## Compiling gpu code

	main=mainCodes/eikonal3D_main.cpp
	eikonal=src/simulations/eikonal/eikonal.cpp
	essentials="$inout $model $utils $geom"
	paramFile="inputs/parameters.txt"
	flags="-acc -fast -ta=tesla,cc60 -g -std::c++11 -lm"

	target=bin/eikonal3D.x 

	pgc++ $flags $main $eikonal $essentials -o $target   

	rm *.o

	./$target $paramFile

	exit 0
;;


-tomography3D_gpu) ## Compiling gpu code

	# python3 src/auxPyCodes/generateTomoModels.py

	main=mainCodes/tomography3D_main.cpp
	eikonal=src/simulations/eikonal/eikonal.cpp
	tomography=src/tomography/tomography.cpp
	essentials="$inout $model $utils $geom"
	paramFile="inputs/parameters.txt"
	flags="-acc -fast -ta=tesla,cc60 -g -std::c++11 -lm"

	target=bin/tomography3D.x 

	pgc++ $flags $main $eikonal $tomography $essentials -o $target   

	rm *.o

	./$target $paramFile

	exit 0
;;

*) ## Message for bad parameter
	echo -e "\033[31mERRO: Option $1 unknown!\033[m"
	echo -e "\033[31mType $0 -h for help \033[m"
	exit 3
;;

esac
